### ISSUE TITLE
Finalize Wireframes

### ISSUE THREAD

**Issue by pdw207** [hackforwesternmass/lightupthemap#3]
https://docs.google.com/presentation/d/1mGQqP7hLOf_mYsbIfLUfszpaIBL1CWWq1wNdxhF_79k/edit#slide=id.g24d7149b46_0_91

**Comment by rick02840** [comment]
This change is partially a design change and partially a major workflow change. Slide 2 is a design change and easy enough to accomplish.  Slide 3 starts a different workflow.

Comparing the 2 workflows:

Current:
New user > creates account (required: email, password, location. representative, senator) > pick and action > take action (phone, email, whatever) > create a light.   
Existing user > login (if not) > pick and action > take action (phone, email, whatever) > create a light.   

Proposed:
User > enter location > pick an action > take action (phone, email, whatever) > create a light.   No login required. 

Proposed workflow is faster for new users, slower for existing users (unless they are not logged-in and forget user/pass).  Location, rep and senator would have to be attached to the light, not to the user, which is OK.  Because of no user account, there is no ability for user to have a permanent record of lights they had created over time.

**Comment by rick02840** [comment]
Branch name for this issue:  **github-issue-3**
That branch has config for adding location, representative and senator fields to the light content type.  Also has config for changing the view that provides json to the map to use the light location rather than the user location. That view is:  admin/structure/views/view/map_lights_json   and output can be seen here:  https://www.lightupthemap.com/json-lights

**Comment by a-pasquale** [comment]
New workflow has been deployed to http://lightupthemap.com
